### ISSUE TITLE
Transforms

### ISSUE THREAD

**Issue by zlapp** [dthiagarajan/simclr_pytorch#1]
Hi thank you for sharing this implementation.
It's very nice to see how succinct it can be with PyTorch lightning.

I think there is an issue with the transforms.
From what I understand, in the original paper for a given image, there are two different augmentations used on the single image to get two different copies.

Since here https://github.com/dthiagarajan/simclr_pytorch/blob/0a674cb8f9b98f7bc87b79f1c94457f729714431/simclr/model.py#L87 the transforms are passed into the Dataset object and not applied within SimCLRDataset here https://github.com/dthiagarajan/simclr_pytorch/blob/0a674cb8f9b98f7bc87b79f1c94457f729714431/simclr/data.py#L24 I believe that the images pairs are the same.

I might be missing something, but I double-checked by comparing the images pixel-wise.

**Comment by dthiagarajan** [comment]
Hi @zlapp, thanks for bringing this up - I think you're absolutely right: I need to be applying the transformations in the `SimCLRDataset` wrapper, as otherwise it's using the same sampled transformation twice, rather than sampling two transformations and applying them separately. Great catch!

**Comment by dthiagarajan** [comment]
Done! Should be addressed in the last commit.

**Comment by dthiagarajan** [comment]
Tested using:

```python train.py --model_name resnet18 --projection_dim 64 --fast_dev_run True --data_dir ~/data```

**Comment by zlapp** [comment]
Awesome! Happy was able to help and thanks for sharing your work again!
